# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-05-30 03:34:05

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Data_raw is expected to be a DataFrame with index as Month (1 to 12) and one column with year as string or int
    df = data_raw.copy()
    df.index.name = 'Month'
    df.reset_index(inplace=True)

    # Try to find the year column name - it might be int 2025 or string '2025'
    year_col = None
    for col in df.columns:
        if str(col) == '2025':
            year_col = col
            break
    if year_col is None:
        raise ValueError("Year column '2025' not found in data")

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=df['Month'],
        y=df[year_col],
        mode='lines+markers',
        name='Total Sales',
        line=dict(color='blue')
    ))

    fig.update_layout(
        title="Monthly Total Sales Trend for 2025",
        xaxis_title="Month",
        yaxis_title="Total Sales",
        xaxis=dict(tickmode='linear', dtick=1, range=[1,12]),
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict