# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-05-30 00:50:59

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Assuming data_raw is a DataFrame with 'Customer Location' and 'Order Count'
    df = data_raw.copy()

    fig = go.Figure(
        data=go.Bar(
            x=df['Customer Location'],
            y=df['Order Count'],
            marker_color='lightskyblue'
        )
    )

    fig.update_layout(
        title="Order Count by Customer Location",
        xaxis_title="Customer Location",
        yaxis_title="Order Count",
        xaxis_tickangle=-45,
        template="plotly_white",
        yaxis=dict(dtick=1)
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict