# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-05-30 01:46:28

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Pivot the data to create a matrix suitable for heatmap:
    # Rows: Customer Location, Columns: Category, Values: Total Sales
    pivot_df = data_raw.pivot(index="Customer Location", columns="Category", values="Total Sales")

    # Ensure consistent order for categories and customer locations for clarity
    category_order = sorted(data_raw["Category"].unique())
    location_order = sorted(data_raw["Customer Location"].unique())

    pivot_df = pivot_df.reindex(index=location_order, columns=category_order)

    # Create heatmap
    fig = go.Figure(data=go.Heatmap(
        z=pivot_df.values,
        x=pivot_df.columns,
        y=pivot_df.index,
        colorscale='Viridis',
        colorbar=dict(title="Total Sales"),
        hoverongaps=False
    ))

    # Update layout with titles and axis labels
    fig.update_layout(
        title="Heatmap of Total Sales by Customer Location and Category",
        xaxis_title="Category",
        yaxis_title="Customer Location",
        yaxis_autorange='reversed'  # to have top customer location at top
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict