# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-05-30 00:53:06

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Since the dataset only provides one mean_order_size per Customer Location,
    # we create synthetic data points around the mean using std_order_size and order_count
    # to simulate the distribution for the box plot.
    # This step mimics the variation around the mean order size per location.
    
    synthetic_rows = []
    for _, row in data_raw.iterrows():
        loc = row['Customer Location']
        mean = row['mean_order_size']
        std = row['std_order_size']
        count = row['order_count']
        
        # Generate synthetic order sizes per location using normal distribution
        # with mean and std, clip to positive values (order sizes can't be negative)
        if count > 1 and std > 0:
            samples = np.random.normal(loc=mean, scale=std, size=count)
            samples = np.clip(samples, a_min=0, a_max=None)
        else:
            samples = np.array([mean] * count)
        
        for val in samples:
            synthetic_rows.append({'Customer Location': loc, 'Order Quantity per Order': val})

    synthetic_df = pd.DataFrame(synthetic_rows)

    fig = go.Figure()

    # Create box plot grouped by Customer Location
    fig = go.Figure()

    for loc in synthetic_df['Customer Location'].unique():
        fig.add_trace(go.Box(
            y=synthetic_df.loc[synthetic_df['Customer Location'] == loc, 'Order Quantity per Order'],
            name=loc,
            boxmean=True
        ))

    fig.update_layout(
        title="Order Quantity Variation per Order by Customer Location",
        xaxis_title="Customer Location",
        yaxis_title="Order Quantity per Order"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict