# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-05-30 01:39:57

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Data_raw is expected to be the dataframe as described
    
    # Melt the dataframe to long format for easier plotting
    df_long = data_raw.melt(id_vars="Payment Method",
                            value_vars=["Clothing", "Electronics", "Footwear", "Home Appliances"],
                            var_name="Product Category",
                            value_name="Average Total Sales")
    
    # Sort categories to keep order consistent
    category_order = ["Clothing", "Electronics", "Footwear", "Home Appliances"]
    payment_methods = data_raw["Payment Method"].unique()

    # Create a grouped bar chart
    fig = go.Figure()

    for payment_method in payment_methods:
        df_sub = df_long[df_long["Payment Method"] == payment_method]
        # Ensure order of categories
        df_sub = df_sub.set_index("Product Category").loc[category_order].reset_index()
        fig.add_trace(go.Bar(
            x=df_sub["Product Category"],
            y=df_sub["Average Total Sales"],
            name=payment_method,
            hovertemplate='%{x}<br>%{y:.2f}<br>Payment Method: '+payment_method+'<extra></extra>'
        ))

    fig.update_layout(
        title="Average Total Sales by Payment Method Across Product Categories",
        xaxis_title="Product Category",
        yaxis_title="Average Total Sales",
        barmode='group',
        xaxis=dict(tickmode='array', tickvals=category_order),
        legend_title_text="Payment Method",
        margin=dict(l=60, r=40, t=80, b=60),
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict